bgcolor = "30; 30; 30"
gcolor = "60; 60; 60"
fgcolor = "200; 200; 200"

[syntax]
casual = ""
keyword1 = "179, 123, 178"
keyword2 = "179, 123, 178"
text = "255, 147, 89"
number = ""
comment1 = "87, 166, 74"
comment2 = "87, 166, 74"
function = ""
class = "179, 123, 178"
interface = ""
decorator = ""
constant = ""
variable = ""
opertor = ""