name = "Lumen"
extensions = [".lm"]

folding = [
	["{", "}"]
]

styles = [
	["\".*?[^\\\\]\"", "string"],
	["\#.*", "comment"],
	["\\b(open|base|raise|record|next|try|except|finally|global|break|not|self|and|is|let|module|or|xor|where|new|do|end|this|if|else|for|in|while|from|return|true|false|void|(:(\\s+)?(?<range>auto)))\\b", "keyword"],
	["\\b(comparable|const|derived|enum|optional|bignum|constructor|num|exception|seq|expando|file|str|vec|bool|map)\\b", "class"]
]

actor = "lumen_actor.lm"